### PR TITLE
Beta to release

### PR DESCRIPTION
**Pull request by ricki-z**

### CODE REVIEW

**Comment by ricki-z** [comment]
DHT22 not working.

**Comment by ricki-z** [comment]
There is a list of firmware files in different languages unter "Firmware einspielen" (in english version "Import firmware")

**Comment by stewecar** [comment]
@ricki-z thanks! Tried the beta version.. great with an OLED display..with page's changing..waiting for the official version.

**Comment by Adorfer** [comment]
But where do i find the beta-images? 
There is multiple languages, but no beta-versions. At least where i am looking. 

Where do i have to look exactly for the beta versions?

**Comment by ricki-z** [comment]
Release version:
http://www.madavi.de/sensor/update/data/latest_xx.bin

Beta version:
http://www.madavi.de/sensor/update/data/latest_beta_xx.bin

xx ist the 2-letter language code

**Pull request closed without merging**
