### PR TITLE
Translation update

### PR DESCRIPTION
**Pull request by ddzieduch**

### CODE REVIEW

**Comment by ricki-z** [comment]
Please push this changes against the beta branch.
The master branch will only get changes made in the beta branch, no direct pull requests.

**Comment by ddzieduch** [comment]
My mistake. @ricki-z @dirkmueller look now.

**Comment by ricki-z** [comment]
You also need to use the beta as source of your changes. At the moment there are changes to Versions.md and other files that would override existing changes.

**Comment by ddzieduch** [comment]
#677

**Pull request closed without merging**
