### PR TITLE
Reduce memory consumption of sendData

### PR DESCRIPTION
**Pull request by dirkmueller**
sendData() had two deep-copy capturing closures, which are
keeping full copies of data and request_headers permanently in memory,
which is extremely wasteful and triggering heap fragmentation.
    
We can simplify the code a bit and also avoid printing the http
reply by default, which removes ~ 200ms request time (waiting for serial).

### CODE REVIEW

**Comment by ricki-z** [comment]
With the space now available we could try to add cert verification. All our servers use Let'sEncrypt certs.  But for this we would need to change to BearSSL.

**Comment by nospam2000** [comment]
> With the space now available we could try to add cert verification.

I would understand that for private data+servers, but what is the benefit of encryption and certificate validation of data which is nevertheless published and available to everyone?

Do you mean server certificate validation or client certificate validation?

**Comment by ricki-z** [comment]
Server cert. Mainly for firmware update. And I think some people in "other" countries would also prefer to send their data only to our servers.

**Comment by dirkmueller** [comment]
I was experimenting a bit with verification, but I would prefer to do that after the arduino core update, as there are some improvements in that area there.

**Pull request merged**
