### PR TITLE
add config option to set Wifi host name

### PR DESCRIPTION
**Pull request by bb-Ricardo**
* defines wifi hostname
* defines mdns name

### CODE REVIEW

**Comment by ricki-z** [comment]
Is this pull request tested on a real "system" (prefered: one with a fresh install, one with an older firmware version updated to the newer one)? We have tried this before and had problems with the config mode with a changed wifi hostname.

**Comment by bb-Ricardo** [comment]
Tested it with a WeMos D1  and everything seems to work. Will test an upgrade with my current NodeMCU which is currently running as sensor.

Test and config with 32 characters
config

As seen from FritzBox
hostname

Zeroconf/bonjour
mdns

**Comment by bb-Ricardo** [comment]
Flashed my NodeMCU this morning. I had to reconfigure it but then all worked as expected. The Firmware was also 1.5 years old so could be caused of changes which happened in between.

**Comment by ricki-z** [comment]
And now please close this pull request and start a pull request to the beta branch as mentioned in the README.md ...

**Comment by bb-Ricardo** [comment]
Closing this one and reopening one against beta

**Pull request closed without merging**
