### PR TITLE
Add send_now variable to DRY up the code

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by ricki-z** [comment]
This won't compile (line 2055: starttimee not defined). And we have to save space on vars, so don't define unnecessary vars.

**Comment by corny** [comment]
Opps, I fixed the error in line 2055. Instead of using a global variable this variable could also be local and passed to `sensorSDS()`.

**Comment by corny** [comment]
Should we introduce a global `send_now` variable or a macro?

**Comment by ricki-z** [comment]
I had changed the code so that your PR couldn't be merged automatically. But I've included your changes in the last version (global var send_now).

**Comment by corny** [comment]
Thanks a lot!

**Pull request closed without merging**
