### PR TITLE
blink LED and read DHT22 w/o parameters when it fails with parameters

### PR DESCRIPTION
**Pull request by njumaen**
I'm quite new to git and new to the project. maybe this helps...

### CODE REVIEW

**Comment by njumaen** [comment]
latest firmware update fixes the DTH issue so I reverted my commits

**Comment by michael-k** [comment]
- `git rebase -i 38f9aef`
- editor opens; remove all commits (those you reverted and the revert commits) you do not want; save and close editor
- fix any conflicts
- `git push -f origin master`

If you get stuck, you can always go back with `git rebase --abort && git reset --hard origin/master` (`--hard` drops all your changes; use `--soft` or `--mixed` to keep them).

**Comment by michael-k** [comment]
Regards opendata-stuttgart/sensors-software#35

**Comment by njumaen** [comment]
@michael-k Thank you!!
@ricki-z Great! Thought about showing it at the header first.

**Comment by michael-k** [comment]
`git config --global core.editor "myeditor --arg"` :)

**Comment by ricki-z** [comment]
If you use auto update, your firmware will be overwritten after restart. If the version string is anything else than the actual firmware, the nodemcu will "update" (even with higher numbers).
With disabled auto update you can use your own fork.

**Pull request closed without merging**
