### PR TITLE
Collect all the persistent configuration variables inside a namespace

### PR DESCRIPTION
**Pull request by fmeerkoetter**
The variables inside the cfg namespace are persistent configuration values.
They have defaults (extdef), they can be changed by the user via the web
interface, the changes are persisted to the flash and read back after reboot.

Wrapping these inside a namespace clearly communicates that a given global
variable is actually a special variable (a cfg variable).

This commit is part of an ongoing effort to give the firmware a bit more structure.

This change does not increase the size of the firmware.

### CODE REVIEW

**Comment by ricki-z** [comment]
@fmeerkoetter
'Remove a global variable' server_name should be made configurable or translateable for international versions in a later release. First tests with that showed some problems. But this was left as a remark.
'Demote first_csv_line from a global into a local static' won't work this was. Setting the variable to true one line in front of the condition makes this always true. So the csv header line would be printed in front of every value line. But it should only be printed once per start of the sensor. So the variable needs to remain global to 'survive' the function call.

**Comment by fmeerkoetter** [comment]
Regarding the demote_csv: the variable is not always true.

Please consider the static storage modifier. It has the effect that the
variable will be initialized with true the first time the code is executed.
If the function is executed a second time (3rd, 4th, ...) it is already
initialized and the true assignment won't happen again.

IMHO the code works

Am Do., 8. Nov. 2018, 23:05 hat Rajko Zschiegner <notifications@github.com>
geschrieben:

**Comment by fmeerkoetter** [comment]
Regarding the server name: I will change the patchsets to make it a global
again, adding your remark why it should be a global as comment.

Am Do., 8. Nov. 2018, 23:05 hat Rajko Zschiegner <notifications@github.com>
geschrieben:

**Comment by ricki-z** [comment]
Regarding the demote_csv: this is C ... ;-) As I mentioned before, too many different languages at the same time.

**Pull request merged**
