### PR TITLE
zDo not set the sample count to 0 at the end of each loop

### PR DESCRIPTION
**Pull request by fmeerkoetter**
We want to count the samples, reset sample_count to 0 at the end of each loop doesn't help.

### CODE REVIEW

**Comment by ricki-z** [comment]
This counts how often the loop is executed per measurement interval. Complete time needed for an interval divided by this is the average time per run through the loop.
We need this for the PPD42NS where we need to know how often the pins are read. And these are samples.

**Comment by ricki-z** [comment]
And it isn't set to zero after every loop. It set to zero only if send_now is true (at the end of each measurement interval).

**Comment by fmeerkoetter** [comment]
You are absolutely right. I missed that additional scope. Makes more sense now ;-)

**Comment by ricki-z** [comment]
But maybe we could put the sending lines to a function to get the loop() shorter. In a second step we could move all inside the "if (send_now)" to an own function. So the structure should be more clear.

**Pull request closed without merging**
