### PR TITLE
Set hostname to Luftdaten-$SENSORID

### PR DESCRIPTION
**Pull request by schinken**
It's easier to identify that device in your wifi controller

### CODE REVIEW

**Comment by ricki-z** [comment]
I think we will use the new name 'airrohr' in one of the next versions.

**Comment by ccoenen** [comment]
has this ever been implemented? If so, this could be closed. if not: why not merge it?

**Comment by ricki-z** [comment]
we need to update all the docs (or multiple versions) if we change the name. So we may change the name in the future but we need time for preparation if we do this.

**Comment by YaguraStation** [comment]
If you need help with docs, let us know.

**Comment by z4y4ts** [comment]
Just a note from someone who speaks no German.

Luftdaten-XXX would make it much easier to identify the network I need because that's where I've got the Firmware from. That's what I intuitively expected to find.

OTOH, Feinstasomething makes no sense on the first encounter so I have to go back to the documentation to know what to look for.

**Pull request closed without merging**
