### PR TITLE
added mqtt publish with RMAP specifications

### PR DESCRIPTION
**Pull request by pat1**
I am a project manager of RMAP (participatory environmental monitoring network) http://rmap.cc.
With this pull request will be possible to publish data on an RMAP server.
It's required https://github.com/knolleary/pubsubclient library.
Only german and italian translation are available.
For now only SDS011 data are published (other data are not required on RMAP platform).
Short instructions:
* register on RMAP to get username and password:
http://rmap.cc/registrazione/register/

* if you do not know you coordinates make a new station on server:
http://rmapv.rmap.cc/insertdata/newstation
 insert your address or use "draw a marker" instrument on map and insert the station name.
You can use the default name "luftdaten"

Follow the standard procedure as for luftdaten.info but in the configuration page activate RMAP send and insert RMAP specifications:
* username
* password
* station name
Save and all is done.

The coordinate are getted from RMAP server, but you can set it manually in configuration page.
To refresh coordinate from server you can delete the coordinate field in configuration page and reboot the station.

### CODE REVIEW

**Comment by ricki-z** [comment]
We won't support mqtt. Every mqtt service is using another data format. And if we start with one service people will ask to add another and another and another service.

AND: our italian sensor owners have a problem with the data usage by your company. As there is no license for our data you should have asked if you could use this. With this message we forbid your company the usage of our data on behalf of our italian users .

**Comment by pat1** [comment]
"As there is no license for our data ..."
???
http://luftdaten.info/impressum/
"Creative Commons „Namensnennung-Weitergabe unter gleichen Bedingungen 3.0 Deutschland (CC BY-SA 3.0)"
We respect the license as you can see at http://rmapv.rmap.cc/network/ and every data is linked to you attribution and licenze.
In your site I find:
"Ziel des Programms ist es, Entwicklungen im Bereich Transparenz, Open Data und Citizen Science zu fördern."
"OK Lab Daten sind Open Data."
So I think we do not have to ask you to use it.
Our project is open hardware e free software based supported by citizen and makers and our data are open data; we are very surprised by your behavior.
We are also very disappointed as we hoped for a profitable scientific collaboration and data and software exchange.

**Comment by ricki-z** [comment]
This is the license for the website http://luftdate.info/ only. Translated:
"The content created by the site operators and works on these pages are subject to the license agreement of the Creative Commons "Attribution-Share Alike 3.0 Germany (CC BY-SA 3.0)".
The important word is PAGES. This is not the license for the published data.

**Comment by pat1** [comment]
ok, so your project is not open.
It's very strange because your data base have an open API to get the data and you document it as right method to get the data and there is no other disclaimer.
We have lost a lot of time planning the use and improvement of your data;  our platform manage only open data for the community.
I suggest you to clarify this in your site because some italian users think the data are open data. 
We are going say this publicly and delete yours data from our server as soon as possible.
Can you clarify to me the licence for the software in github ? We are working on improvements in our fork for calibration and other problems we have found and do not  want to go in the same problem.

**Comment by ricki-z** [comment]
Our software and our data is free for private use. By now it's not allowed to use them for any published 'product' without permission.
And about the loss of time: You could have asked us just like anybody else.

**Comment by pat1** [comment]
All data getted from lufdaten.info are removed from RMAP.
As your software license for software you are not allowed to stay on github any more:
https://help.github.com/articles/licensing-a-repository/
And we have to check for other license infringement.

**Comment by ricki-z** [comment]
As I have written: We haven't decided 'BY NOW', which open source license we will choose.
But as this license may be a very restrictive or incompatible license, you shouldn't use the software for own 'products' by now.

**Comment by ricki-z** [comment]
And the data is completely independent from this license.

**Comment by pat1** [comment]
You need to issue a license before publishing the software to github, not after; so you do not have a lot of time.

To your knowledge you have to ask to remove your data from:
https://public.opendatasoft.com/explore/embed/dataset/api-luftdateninfo/map/?q=&refine.timestamp=2017%2F11&static=false&datasetcard=false&location=8,44.44751,12.12067&basemap=jawg.streets
https://public.opendatasoft.com/api/v1/console/datasets/1.0/search/?q=luftdateni
They also understood that the license is "Public Domain" and I can get the data from opendatasoft API

**Comment by pathmapper** [comment]
@ricki-z I also understood that the data is Open data in the sense of https://en.wikipedia.org/wiki/Open_data

> Open data is the idea that some data should be freely available to everyone to use and republish as they wish, without restrictions from copyright, patents or other mechanisms of control. 

because it is written on the main page of luftdaten info.

Adding licenses for data and software would be good for clarification.

image

**Comment by ricki-z** [comment]
But you shouldn't use even open data without knowledge of the data quality.  And as we haven't published any information about this until now you should ask the publisher. This is the point of discussion with Pat. Both http://rmapv.rmap.cc/ and https://public.opendatasoft.com/ publish this data without an information, that this data may be from unreliable sources. On rmap.cc our data is publish equal to data made with professional equipment without any differentiation.
So we would like to clarify the accuracy of our data before we publish a license.

**Comment by ricki-z** [comment]
License for airrohr-firmware is added (GPL v3). Beta branch will be updated with next push. Other parts of the repo may have other licenses (i.e. directories with copies of library published with different license, ...).

**Comment by ricki-z** [comment]
License for data (Database Contents License (DbCL) v1.0) will be added today to the website.

**Comment by stkdiretto** [comment]
Is there any kind of community-led governance as to the exact Free/Open nature of the data?

**Comment by ricki-z** [comment]
What exactly do you mean?

**Comment by stkdiretto** [comment]
I became aware of the licensing discussion only yesterday, and, to be honest, I am rather flummoxed by the publicly available reasoning behind the licensing decision. My question is, how decisions of this scope are made within the project. Namely: Who makes these decisions, and is there any way the community (which, in my opinion, is a very important asset of the project):

- becomes aware of pending decisions
- may involve themselves in the discussion leading towards a decision
- may involve themselves in the discussion itself

I myself consider the license chosen for the collected data to be harmful to Open Data endeavours and would have liked there to have been a discussion and consensus e.g. on a level of the Code for Germany network or a similar platform.

**Comment by ricki-z** [comment]
As you may remember we tried to discuss this at the OK slack. No one there could tell us what license would be 'ideal' for our data.
The choosen license is a project of the Open Knowledge Foundation so they should be okay with that (https://opendatacommons.org/about/).

**Comment by stkdiretto** [comment]
Yes, I remember, which makes me all the more confused ;) A quick search in Slack showed me one question as to the unclear licensing situation dating to september 2017, and one discussion from end of january 2018.

I was not aware that a license had been chosen and selected in the interim time, and I am not aware of any other discussion having taken place. This is what I meant: Is there any consensus on the structure and process regarding choices and decisions of this scope to be made? How are these issues raised? How and where do discussions take place? Who is to decide in the end?

As to the licensing issue itself: As far as I can tell from Slack, several arguments were made in favor of choosing CC-0 for the data. ODC is a project by Open Knowledge International, *not* OKFDE, and just because they created the license does not mean they automatically condone its use for *any* use case ;) As stated above, I consider choosing this license to be harmful, since 

- it does not include sui-generis rights, therefore potentially rendering re-use of the data impossible within the EU
- it is *based* on droit-d'auteur-type rights and would therefore only be legally binding if we subscribe to the idea of automatically gathered factual data being subject to (EU) copyright law. This itself is a very dangerous precedent to be made by any open-data working group. [See also](http://simia.net/wiki/Free_data)

I was under the impression that choosing CC-0 was the result of the Slack discussion of january 23rd in Slack. Whatever the outcome – I suggest choosing a more formalized decision process for the future, so we won't have to search through minutiae of (not publicly accessible) Slack channels for the future ;)

**Pull request closed without merging**
