### PR TITLE
Advertise in AP mode the sensor via final MDNS name

### PR DESCRIPTION
**Pull request by dirkmueller**
Remove
some code duplication/indentation errors as well as
ensuring that our captive DNS responses are not cached
by setting TTL to 0.

### CODE REVIEW

**Comment by dirkmueller** [comment]
You're correct on this, but as we install a dns server that resolves anything to the host ip, it doesn't matter. 

Another thought I just had is that we can name this already like the host will be called in STA mode, this way you might be able to easily reaccess it after reboot (same hostname)

We could even install some js that will refresh until the page until it becomes available again with the same hostname but different ip and do a 2nd stage configuration.

**Comment by ricki-z** [comment]
Sorry, my fault. I had still the commit with the DNS server removal in mind.
A first step to the js refresh could be a forwarding to the "future" hostname (including the chipID) when airrohr.local is requested. For the refresh we need to test the restart time. (And a hint that this won't work on a freshly flashed system that wasn't power cycled).

**Comment by ricki-z** [comment]
Do we need the MDNS in config mode if there is a DNS server? There should be only one client and this client should have access to the sensor wifi only. So a DNS request for 'airrohr.local' should be resolved to the sensor IP anyhow.

**Comment by dirkmueller** [comment]
@ricki-z interestingly further testing showed that for some combinations of OS/browsers a "*.local" is never resolved via DNS, only via MDNS.

So I have updated the change to only add MDNS and not change anything else. Again the point of adding MDNS is that we can add some JS to the client side redirecting to that hostname to be able to seamlessly able resume the browsing session after wifi switchover.

**Pull request merged**
