### PR TITLE
Replace a number of defines with a typesafe enum

### PR DESCRIPTION
**Pull request by fmeerkoetter**

### CODE REVIEW

**Comment by ricki-z** [comment]
And AGAIN: 'enum class' does not work with the Arduino IDE!!!

**Comment by fmeerkoetter** [comment]
> And AGAIN: 'enum class' does not work with the Arduino IDE!!!

I dislike being shouted at. I explained in the other PR why I created this PR.

Did you try *this* specific patch?

For some reason *this* patch works for me both in Arduino IDE and Platformio.
I wrote my first comment after I made this observation.

Later I noticed your revert on the beta branch. I reverted that revert and noticed that now my Arduino IDE had a problem.

This is strange. Both IDEs (Arduino und Platformio) are using 1:1 the very same toolchain.
```
/home/fmee/.platformio/packages/toolchain-xtensa/bin/xtensa-lx106-elf-g++ -v
Using built-in specs.
COLLECT_GCC=/home/fmee/.platformio/packages/toolchain-xtensa/bin/xtensa-lx106-elf-g++
COLLECT_LTO_WRAPPER=/home/fmee/.platformio/packages/toolchain-xtensa/bin/../libexec/gcc/xtensa-lx106-elf/4.8.2/lto-wrapper
Target: xtensa-lx106-elf
Configured with: /home/igrokhotkov/xtensa/crosstool-NG/.build/src/gcc-4.8.2/configure --build=x86_64-build_unknown-linux-gnu --host=x86_64-build_unknown-linux-gnu --target=xtensa-lx106-elf --prefix=/home/igrokhotkov/xtensa/crosstool-NG/builds/xtensa-lx106-elf --with-local-prefix=/home/igrokhotkov/xtensa/crosstool-NG/builds/xtensa-lx106-elf/xtensa-lx106-elf/sysroot --disable-libmudflap --with-sysroot=/home/igrokhotkov/xtensa/crosstool-NG/builds/xtensa-lx106-elf/xtensa-lx106-elf/sysroot --with-newlib --enable-threads=no --disable-shared --with-pkgversion='crosstool-NG 1.20.0' --disable-__cxa_atexit --with-gmp=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-mpfr=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-mpc=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-isl=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-cloog=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-libelf=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --enable-lto --enable-target-optspace --disable-libgomp --disable-libmudflap --disable-nls --disable-multilib --enable-languages=c,c++
Thread model: single
gcc version 4.8.2 (crosstool-NG 1.20.0)
```
vs.

```
 /home/fmee/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++ -v
Using built-in specs.
COLLECT_GCC=/home/fmee/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/xtensa-lx106-elf-g++
COLLECT_LTO_WRAPPER=/home/fmee/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/bin/../libexec/gcc/xtensa-lx106-elf/4.8.2/lto-wrapper
Target: xtensa-lx106-elf
Configured with: /home/igrokhotkov/xtensa/crosstool-NG/.build/src/gcc-4.8.2/configure --build=x86_64-build_unknown-linux-gnu --host=x86_64-build_unknown-linux-gnu --target=xtensa-lx106-elf --prefix=/home/igrokhotkov/xtensa/crosstool-NG/builds/xtensa-lx106-elf --with-local-prefix=/home/igrokhotkov/xtensa/crosstool-NG/builds/xtensa-lx106-elf/xtensa-lx106-elf/sysroot --disable-libmudflap --with-sysroot=/home/igrokhotkov/xtensa/crosstool-NG/builds/xtensa-lx106-elf/xtensa-lx106-elf/sysroot --with-newlib --enable-threads=no --disable-shared --with-pkgversion='crosstool-NG 1.20.0' --disable-__cxa_atexit --with-gmp=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-mpfr=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-mpc=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-isl=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-cloog=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --with-libelf=/home/igrokhotkov/xtensa/crosstool-NG/.build/xtensa-lx106-elf/buildtools --enable-lto --enable-target-optspace --disable-libgomp --disable-libmudflap --disable-nls --disable-multilib --enable-languages=c,c++
Thread model: single
gcc version 4.8.2 (crosstool-NG 1.20.0)
```

**Comment by ricki-z** [comment]
At first sorry for shouting.
The PR was closed for me. So I didn't look at this. And your comment came just at the time of my comment. For me you tried to make the same change without reading my first comment.
To the different sizes:
There seem to be two versions of the library for the SSD1106 OLED displays with the same name. Maybe there is some difference between them and platformio is selecting the one with the larger footprint.

**Comment by fmeerkoetter** [comment]
Understood and accepted.  :-)

Am So., 28. Okt. 2018, 22:30 hat Rajko Zschiegner <notifications@github.com>
geschrieben:

**Pull request merged**
