### PR TITLE
Rebase airrohr-firmware

### PR DESCRIPTION
**Pull request by Warukira**
I have rebased, please consider changes.

### CODE REVIEW

**Comment by ricki-z** [comment]
Could you please push this against our beta branch? we don't merge pull requests into the master directly.
OTA should be enabled by default. Most of our 13.000 devices that use this firmware are using OTA.
InfluxDB servername shouldn't be set to another name as influx.server. Many users are activating nearly every API option. And I don't know if your AWS account limits can handle this.
Why is the measurement name for the InfluxDB data removed?
And please remove all changes to the esp8266-arduino directory. This part isn't maintained anymore. So it's also not tested (or i.e. changed to actual server names).
The static files should also be removed. We don't have this directory. And the pinouts are copyrighted.

**Comment by ricki-z** [comment]
@Warukira Is there any chance that you are reacting on my comment?

**Comment by Warukira** [comment]
Hi Rajko,

Thank you for the feedback. I will action the requests as soon as I can.

Regards,
Warukira.

**Comment by Warukira** [comment]
Hello Rajko,

Kindly close this PR. Let me clear out my current backlog, and do the PR as
requested earlier on this thread. Thanks.

Regards,

Warukira.

**Pull request closed without merging**
