### PR TITLE
Create multi language interface.

### PR DESCRIPTION
**Pull request by darcoto**
According the feature described in #64 I suggest this decision: 

Excluded all texts from main file to external files (named as intl_*.h) and replacing with constants. One file for every language. Currently available three languages - German, English and Bulgarian. 

On build process:

- If build is made with platformio (according this feature https://github.com/opendata-stuttgart/sensors-software/pull/68), the result is  **three firmware files** (firmware_de, firmware_en, firmware_bg.bin)  
- if build is made Arduino, the result is one firmware with German language.

_This approach is most effective for memory optimization against all language in the one firmware._ 

To switch the language user must change the firmware. This can be done very easy via auto update option. Just change current language from Configuration Page and restart the device. On restart device check for new version (if enable) and can download firmware with selected language (I will make another pull request with necessary changes in api.madavi.de/update/firmware.php)

New language can be add very easy. If the PR is accepted, I would write necessary documentation.

Addition changes:
Small UI changes for html optimization and better user expirience 

Please, make a review to this PR and comment. I am ready to change parts that are not suitable to your roadmap. I believe it will help to promote the initiative

### CODE REVIEW

**Comment by darcoto** [comment]
To download selected language/firmware on change, this PR must be approved too (https://github.com/opendata-stuttgart/madavi-api/pull/3)

**Comment by ricki-z** [comment]
Will start with that. Firmware version could be changed to NRZ-2017-XXX-DE for german and equivalent for other languages. If LANG is set it could be added to firmware-version on update request.
In the update script the (new) version string could be split in NRZ + year + version + lang. With that we could add a switch in the wifi config for the available languages.

**Comment by darcoto** [comment]
OK.
Just to clarify:
1. "Firmware version could be changed to NRZ-2017-XXX-DE"
Which places:
 - in parameter in update request 
 - on screen, 
 - in config file, 
 - in JSON request sent to API

**Comment by ricki-z** [comment]
I've seen, that you changed the request to the update server. Your solution is much more easier to implement as my first thoughts. So the renaming of the firmware version is obsolete.

**Comment by ricki-z** [comment]
Can't get a working version with platformio. please see #77

**Pull request merged**
