### PR TITLE
Adding a missing library

### PR DESCRIPTION
**Pull request by liutikas**
Clean up the list of libraries needed for the project

To be able to compile the project I need to also install Adafruit SHT31 library.
Also add a space between the two lists otherwise markup renderer puts `Manuell zu installieren` on the line above.

### CODE REVIEW

**Comment by ricki-z** [comment]
Please push this against the beta version.

**Comment by liutikas** [comment]
Changed it to push against `beta` branch.

**Comment by liutikas** [comment]
Can this be merged now? Am I missing anything?

**Comment by dirkmueller** [comment]
@liutikas might not happen before christmas, @ricki-z  is on vacation. it's fine, thanks for the contribution!

**Pull request merged**
